###
GET http://localhost:8000/api/user
Content-Type: application/json

###
GET http://localhost:8000/api/user/1
Content-Type: application/json

###
POST http://localhost:8000/user
content-Type: application/json

{
  "name": "http test",
  "email": "http.test@email.com"
}

###
PATCH http://localhost:8000/api/user/1
Content-Type: application/json

{
  "email" : ""
}

### 
DELETE http://localhost:8000/api/user/5
Content-Type: application/json
